language: node_js
dist: trusty
group: deprecated-2017Q4
node_js:
  - "6.10"
  - "8.0.0"

script:
  - npm run lint
  - npm test -- --coverage --testResultsProcessor ./node_modules/jest-junit && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls